# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-server-client:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start the server
      run: |
        nohup python server.py &
      env:
        PYTHONUNBUFFERED: 1

    - name: Run the client
      run: |
        python client.py
